server:
  http_listen_port: 9080
  grpc_listen_port: 0

# File to store positions so that restarted promtail picks up where it left off.
positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MAIN_INSTANCE_PRIVATE_IP}:3100/loki/api/v1/push"
    tenant_id: "default"

scrape_configs:
  # Scrape system logs from /var/log
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: client
          __path__: /var/log/**/*.log

  # Scrape Docker container logs
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: client
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - output:
          source: labels
          
      - timestamp:
          source: time
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - UnixMs
          location: UTC
      
      - docker: {}
      
      - output:
          source: labels
      
      - regex:
          expression: '(?P<container>.+)'
          source: container_name
      
      - output:
          source: labels
      
      - labels:
          container:
      
      - output:
          source: labels
      
      - labeldrop:
          - filename
          - container_name
          
      - output:
          source: labels
