server:
  http_listen_port: 9080
  grpc_listen_port: 0

# File to store positions so that restarted promtail picks up where it left off.
positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MAIN_INSTANCE_PRIVATE_IP}:3100/loki/api/v1/push"
    tenant_id: "default"

scrape_configs:
  # Scrape system logs from /var/log
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: client
          __path__:
            - /var/log/syslog         # Critical system log (Ubuntu) for tracking EC2 health events
            - /var/log/messages       # Critical system log (CentOS/Amazon Linux) for instance health monitoring
            - /var/log/dmesg          # Kernel messages capturing hardware and boot issues
            - /var/log/cloud-init.log # Cloud-init log for tracking EC2 initialization and related status events

  # node-exporter container
  - job_name: node-exporter
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: client
          container: node_exporter
          __path__:
            - /var/lib/docker/containers/*node_exporter*/*.log

  # promtail container
  - job_name: promtail
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: client
          container: promtail
          __path__:
            - /var/lib/docker/containers/*promtail*/*.log

  # ping-agent container
  - job_name: ping-agent
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: client
          container: ping_agent
          __path__:
            - /var/lib/docker/containers/*ping_agent*/*.log

  # Other Docker containers (e.g. DB)
  - job_name: other-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: client
          container: other
          __path__:
            - /var/lib/docker/containers/*.log

    # Simple pipeline to handle timestamps
    pipeline_stages:
      - timestamp:
          source: time
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - UnixMs
          location: UTC
